# Generated by Django 3.1.4 on 2021-01-11 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0009_post_snippet'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='deader_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
