# Generated by Django 3.1.4 on 2021-01-11 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0010_post_deader_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='deader_image',
            new_name='header_image',
        ),
    ]
